<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>omacut</AssemblyName>
    <PackageId>Omacut.App</PackageId>
    <RootNamespace>Omacut.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Omacut\Omacut.csproj" />
  </ItemGroup>
</Project>
